### ISSUE TITLE
Use the MNE logger to set the verbosity

### ISSUE THREAD

**Issue by mscheltienne** [sappelhoff/pyprep#105]
I have been using PyPREP a bit (version 0.3.1, pip install) and I really like it for now.
Would it be possible to add a verbose argument to limit the prints? Alternatively, moving the print to a logger with a `set_log_level` function would work out too.

Example: `print("Executing RANSAC\nThis may take a while, so be patient...")`

When running a preprocessing pipeline with several steps, one of which is PyPREP, the relevant logging from the pipeline can be completely overwhelmed by the prints from PyPREP, especially if you run it as I do on e.g. 40 cores at once.

**Comment by sappelhoff** [comment]
> I have been using PyPREP a bit (version 0.3.1, pip install) and I really like it for now.

oh, please install and use the development version for now:

`pip install git+https://github.com/sappelhoff/pyprep.git@master`

as we note in the README: https://github.com/sappelhoff/pyprep#installation

We are preparing for a bigger release, and the current development version fixes many inaccuracies and problems that are still there in the 0.3.1 release.

cc @a-hurst @yjmantilla should we maybe just release in the current state and do the remaining features in 0.5 or 0.4.1 or so? I am concerned that too many people will use a standard pip install and end up with version 0.3.1

---

Regarding your proposal @mscheltienne --> yes, I think we could switch to using the MNE logger :thinking: then you could easily set any log level you want. But it's gonna be a bit of work to consistently apply that throughout the code base.
