### ISSUE TITLE
Question: using pyprep.NoisyChannels on numpy arrays

### ISSUE THREAD

**Issue by sunshineinsandiego** [sappelhoff/pyprep#126]
Hi - First, thanks for making the PREP pipeline available in python! I have a set of 19-channel EEG recordings in numpy array format (19ch x 18K samples), and I would like to automatically eliminate bad channels from these arrays before further processing. Is it possible to use pyprep.NoisyChannels to identify the channels (i.e. rows) that should be eliminated before EEG analysis?  Thanks!

**Comment by sappelhoff** [comment]
hi @sunshineinsandiego, please follow this tutorial to turn your numpy array into an MNE data structure first ("raw"): https://mne.tools/stable/auto_tutorials/simulation/10_array_objs.html

PyPREP only works on MNE raw data structures, not on numpy arrays.

Cheers!
