### ISSUE TITLE
Issue with RawBrainVision

### ISSUE THREAD

**Issue by Sam54000** [sappelhoff/pyprep#127]
Hi, thank you for this amazing pipeline which works well with mne.
I have an issue though, I am working with mne-bids and my files are converted into BrainVision format. Therefore when I read back my files and try to run PrepPipeline I run into an error
 ```
find_noisy_channels.py", line 92, in __init__
    self.n_samples = raw._data.shape[1]
AttributeError: 'RawBrainVision' object has no attribute '_data'
```
I might found a walkaround by doing `raw._data = raw.get_data()` but I don't think it is a sustainable solution. Someone have any idea?

**Comment by sappelhoff** [comment]
Hi, thanks for the report. I am really surprised that the `_data` attribute is not available. I also wonder how mne-bids could have an impact on this. Can you replicate this problem in a minimal working example? Preferably using a file available from mne (e.g., ["sample"](https://mne.tools/dev/overview/datasets_index.html#sample))

**Comment by sappelhoff** [comment]
Can you also share some more of the code you use? Also, is your raw object "preloaded" (see https://mne.tools/stable/generated/mne.io.Raw.html) before you pass it to pyprep?
