### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hoechenberger** [sappelhoff/pyprep#136]
Hello @sappelhoff, I see there are a lot of fixes in `master` (should maybe be renamed to `main` if you have time?) since the last release. Would you care to cut a new release sometime soon? Until then, I suppose I'll have to use the dev version :) Thanks

**Comment by sappelhoff** [comment]
I'll look into it 👍

**Comment by sappelhoff** [comment]
The default branch is now called `main`. `master` has been deleted.

**Comment by sappelhoff** [comment]
done: https://pypi.org/project/pyprep/ enjoy :)

**Comment by hoechenberger** [comment]
👌
