### ISSUE TITLE
Implementing the entire PREP pipeline

### ISSUE THREAD

**Issue by Nick3151** [sappelhoff/pyprep#2]
Hi! We'd like to implement the entire PREP pipeline, which will include:

1. Bug fixing of Noisydata class
2. Feature enhancement by adding filtering, line noise removal and robust referencing.
3. Integrating all the steps into one function

**Comment by sappelhoff** [comment]
Hi @Nick3151 - that sounds great to me. Who is "we"? How do you want to work on this?

**Comment by Nick3151** [comment]
And maybe we could get pyprep merged into MNE in the future.

**Comment by sappelhoff** [comment]
sounds very good, let's continue the discussion in https://github.com/mne-tools/mne-python/issues/7049

**Comment by adam2392** [comment]
@sappelhoff How do you feel that these folks, @Nick3151 and two others work on a PR into the forked version of this in https://github.com/NeuroDataDesign/pyprep and then we submit a PR here?

Or should we directly try to address the fixes mentioned here and in the discussion in mne-tools/mne-python#7049 with a direct PR in the main repo?

Let us know your thoughts.

**Comment by sappelhoff** [comment]
I think your first suggestion works well. That way you can work independently of any GitHub rights you may need to move forward.

It'd be great to tag me occasionally when there is new stuff you integrate, ... that way I won't be too overwhelmed once you make a PR from your fork to this repo :-)
