### ISSUE TITLE
Does pyprep do the high-pass-filter and interpolation automatically?

### ISSUE THREAD

**Issue by guishuyunye-lyw** [sappelhoff/pyprep#37]
Dear pyprep group
I try to compare the design difference between prep pipeline between pyprep and original on in eeglab. I am a little confused about whether pyprep work like original version, which contain a postprocess.m file including postprocess(interpolate the bad channels if you want to and high-pass filter if you want to).

**Comment by sappelhoff** [comment]
perhaps @yjmantilla can help here.

**Comment by yjmantilla** [comment]
Boy the comparing stuff is THE RABBIT HOLE. 

pyprep is more close to the core functionality of the PREP, it doesn't cover all the options but the fundamental ones.

Regarding this postprocess file in my understading it allows to:

- HP filter
- remove interpolated channels
- cleanup metadata

Now, pyprep does not include this functionality but it is easy to do it applying mne functions to the raw object returned by pyprep.

Assuming this context
```
prep = PrepPipeline(raw, prep_params, montage)
prep.fit()
```
You can extract the raw processed object (that is after a .fit() was successfully done)
```
EEG = prep.raw.copy()
```
HP filter --> Simply an mne filter, most probably around 1 Hz ie :

```
        EEG = mne.filter.filter_data(
            EEG, sfreq=sample_rate, l_freq=1, h_freq=None
        )

```

- remove interpolated channels --> drop the channels interpolated which are in prep.interpolated_channels attribute

```
EEG.drop_channels(prep.interpolated_channels)
```

Im not entirely sure what the cleanup data does though.

**Comment by sappelhoff** [comment]
@guishuyunye-lyw I am closing this now. Please respond or reopen if you have unresolved questions or ocmments :)
