### ISSUE TITLE
[MAINT] GitHub PR template should make use of HTML comments

### ISSUE THREAD

**Issue by sappelhoff** [sappelhoff/pyprep#47]
The [Pull Request Template](https://github.com/sappelhoff/pyprep/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

is written completely in Markdown ... but it contains parts that contributors are supposed to delete, such as 

> Thanks for contributing. If this is your first time, please make sure to read the contributing guideline.

These parts should be written as an html comment, so that if these parts are accidentally **not** deleted, they do at least not show up in the opened PR, like here:

![image](https://user-images.githubusercontent.com/9084751/101238139-7b0cad00-36de-11eb-921c-500e0626f035.png)

Html comment: 
```
 <!--This is a comment. Comments are not displayed in the browser-->
```

Furthermore, there should be an additional point in the template, asking contributors to please pay attention to the "development install instructions" --> https://github.com/sappelhoff/pyprep#installation

**Comment by yjmantilla** [comment]
such disrespect, that guy should read before posting
