### ISSUE TITLE
"Bad by flat" threshold differs between PyPREP and Matlab PREP

### ISSUE THREAD

**Issue by a-hurst** [sappelhoff/pyprep#59]
In Matlab PREP, the criteria for a "flat" channel are that it either has a median absolute deviation below `10e-10` or a standard deviation below `10e-10`.

In PyPREP this is mis-copied over as `1e-10`, but there's an additional difference in that MNE and EEGLAB scale their raw data values differently, such that the first 2 samples in MATLAB are

`[-3.7068, -4.8012, ...]`

whereas in MNE they're

`[-3.70680070e-06, -4.80121040e-06, ...]`. 

Unless I'm doing the math wrong in my head, the correct equivalent threshold to use for PyPREP would therefore be `10e-16`.

**Comment by sappelhoff** [comment]
> Unless I'm doing the math wrong in my head, the correct equivalent threshold to use for PyPREP would therefore be 10e-16.

Sounds good, but let's make it `1e-15`, and add a comment `# corresponds to 10e-10µV from PREP in Matlab`. I think it's bad practice to do `10e-10`, because you might as well go crazy and do `100e-11` or `1000e-12` then, `1e-9` is way clearer.
